[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
remappings = ["@ensdomains/=node_modules/@ensdomains/"]
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200
via_ir = false

# Gas reporting
gas_reports = ["*"]

# Test configuration
test = "test"
cache_path = "cache_forge"

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000 }

# RPC endpoints for different networks
[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
goerli = "https://eth-goerli.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
polygon = "https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
mumbai = "https://polygon-mumbai.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
anvil = "http://127.0.0.1:8545"

# Default to Sepolia for development and testing
default_rpc_url = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

# Etherscan API keys for contract verification
[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
goerli = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}", chain = 11155111, url = "https://api-sepolia.etherscan.io/api" }
polygon = { key = "${POLYGONSCAN_API_KEY}" }
mumbai = { key = "${POLYGONSCAN_API_KEY}" }

# Formatting configuration
[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
